### ISSUE TITLE
mac time issue

### ISSUE THREAD

**Issue by skia92** [guarinogabriel/Mac-CLI#66] opened 2016-07-06 01:06 UTC
While I type some words in Terminal, I experience kind of jamming issue.
Let say I want to type some words in Terminal like this
```
My name is skia92
```
but Terminal shows me 
```
My nae is skia92
```
In this case, even though I recognise this as "My nae is skia92", Terminal still interpret string as "My name is skia92"

I think this problem happen because of sleep function. This is not a critical issue but quite uncomfortable.
Can you enhance this?

**Comment by guarinogabriel** [comment] 2016-07-07 01:31
Hi there!

Sure, I will take a look at this issue to get it resolved.

Best regards.
Gabriel

**Comment by guarinogabriel** [comment] 2016-07-08 01:56
I'm closing this Github Issue since I wasn't able to reproduce the problem. I don't think it's related to Mac CLI, but if you are still experiencing the issue let me know and please provide additional information for debugging. Thanks!

**Closed by guarinogabriel** 2016-07-08 01:56 UTC
