### ISSUE TITLE
Make a brew package for mac-cli

### ISSUE THREAD

**Issue by dbkaplun** [guarinogabriel/Mac-CLI#28] opened 2016-06-27 18:06 UTC
Please. :)

**Comment by guarinogabriel** [comment] 2016-06-28 00:34
@dbkaplun Absolutely! That is a great idea and it will implemented soon.

**Comment by sheerun** [comment] 2016-06-28 10:27
I refuse to install it without homebrew ;)

**Comment by romeroabelleira** [comment] 2016-06-30 07:45
First thing would be to tag a version, so that a hombrew formula can be written against it.

**Comment by guarinogabriel** [comment] 2016-06-30 10:15
@romeroabelleira Sure. You can move forward with that and write one, your contribution is very much appreciated! I will mark this as "in progress" then. Thanks!

**Comment by romeroabelleira** [comment] 2016-06-30 12:05
Great 😀
`$ git tag v0.1` then `$ git push origin --tags` and I'll get going.

**Comment by sheerun** [comment] 2016-06-30 12:06
Please use semver and `git tag v0.0.1` or even better `git tag v1.0.0` :)

**Comment by guarinogabriel** [comment] 2016-07-03 04:52
Hi @romeroabelleira,

I pushed the following tag:
`* [new tag]         v1.0.0 -> v1.0.0`

Thanks for your contribution!

**Comment by guarinogabriel** [comment] 2016-07-04 23:47
@romeroabelleira Please let me know if the PR is in progress. Thanks! :)

**Comment by romeroabelleira** [comment] 2016-07-05 08:35
I’ll start this evening (~ 19:00 CEST). I’ll keep you posted. 👍

**Comment by guarinogabriel** [comment] 2016-07-05 22:58
@romeroabelleira Thanks!

**Comment by ZakariaRidouh** [comment] 2016-07-06 15:50
Any update on this?

Thanks! 😃😃😃

**Comment by romeroabelleira** [comment] 2016-07-07 09:52
I dropped the ball there. It's been a hectic couple of days. Anyway here's how far I got:
I can't use `mac-cli/tools/install` because it throws an error. Understandable, since it tries to clone the repo and then configure the tool. I'm under the impression that it's bad form to ask for user input during brew install (is this accurate?), so an info text with an instruction to run an `offline-install` script would probably be good enough.

Unless somebody disagrees, the next step would be to write `mac-cli/tools/offline-install`.

**Comment by romeroabelleira** [comment] 2016-07-07 14:33
Confirmed:

> We don’t allow interactivity during install in official taps because it breaks unattended installation. HTH!

Source: https://twitter.com/MacHomebrew/status/751060331573628929

**Comment by guarinogabriel** [comment] 2016-07-11 13:23
@romeroabelleira I think we should modify the installation script to not include the wizard.
The wizard could be run with this command: `mac config`

What are your thoughts?

**Comment by romeroabelleira** [comment] 2016-07-11 16:01
That sounds perfect. From what I've seen at a glance you'll have to remove git clone, then stuff like at line 81 that depends on a non-homebrew install path and you want to avoid installing homebrew itself :)

**Comment by ZakariaRidouh** [comment] 2016-07-14 20:57
Any news? Haha thanks!

**Comment by guarinogabriel** [comment] 2016-09-06 20:07
I will close this issue. I decided to prioritize the wizard instead of brew. The wizard is key in order to setup Mac CLI easily.

**Closed by guarinogabriel** 2016-09-06 20:07 UTC
Labels: enhancement, in progress
